# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_auto_20171115_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actioncondtion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='ActionCondtion',
        ),
    ]
